name: 🖤 Black

on:
  workflow_call:
    inputs:
      python_version:
        description: The version of python to setup
        default: 3.x
        type: string

jobs:
  black:
    name: ⬛ Black Formatter
    runs-on: ubuntu-latest

    steps:
      - name: 📰 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip

      - name: 🏴 Install black
        run: pip install black

      - name: 🎱 Run Black
        run: black -S --check --diff --color .
