name: 📦 Release

on:
  workflow_call:

jobs:
  release:
    name: 📝 Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: 📰 Checkout
        uses: actions/checkout@v5

      - name: 📦 Create draft release from milestone
        uses: WGBH-MLA/milestones@main
