name: 📖 Publish to PyPi
# Reusable Publish to PyPi GitHub Action
# This should work, but doesn't because PyPi trusted publishing requires reusable workflows to be in the same repository as the workflow that calls them.
# https://github.com/pypi/warehouse/issues/11096
# Current workaround is to copy this file into the repository that calls it.
# Example: https://github.com/WGBH-MLA/sonyci/blob/main/.github/workflows/publish.yml
on:
  workflow_dispatch:
  # push:
  #   tags:
  #   - '*'

jobs:
  build:
    name: 📦 Build package
    runs-on: ubuntu-latest
    steps:
    - name: 📰 Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: 😎 Install uv
      uses: astral-sh/setup-uv@v7

    - name: 🏗️ Build package
      run: uv build

    - name: 🛫 Export build files
      uses: actions/upload-artifact@v6
      with:
        name: dist
        path: dist

  publish:
    name: 🗞 Publish package
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      # Add the url to your package on PyPi here
      # url: https://pypi.org/p/PACKAGE-NAME
    permissions:
      id-token: write
    steps:
    - name: 🛬 Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: dist

    - name: 🗞 Publish package
      uses: pypa/gh-action-pypi-publish@release/v1